### ISSUE TITLE
Reduced functional based on FEniCS NewtonSolver cant use reduced functional due to parameters.to_dict()

### ISSUE THREAD

**Issue by jorgensd** [dolfin-adjoint/pyadjoint#1]
Parameters.to_dict() does not unravel the parameter values, and can thus not be reused in recomputations.
Running `tests/migration/burgers_oo/burgers_oo.py` with an additional line `Jhat(ic)`
produces the following error:
```
Traceback (most recent call last):
  File "burgers_oo.py", line 69, in <module>
    Jhat(ic)
  File "/home/fenics/shared/pyadjoint/tape.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/home/fenics/shared/pyadjoint/reduced_functional.py", line 135, in __call__
    blocks[i].recompute()
  File "/home/fenics/shared/pyadjoint/block.py", line 351, in recompute
    prepared)
  File "/home/fenics/shared/fenics_adjoint/solving.py", line 558, in recompute_component
    return self._forward_solve(lhs, rhs, func, bcs, **self.forward_kwargs)
  File "/home/fenics/shared/fenics_adjoint/solving.py", line 543, in _forward_solve
    backend.solve(lhs == rhs, func, bcs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dolfin/fem/solving.py", line 265, in _solve_varproblem
    solver.parameters.update(solver_parameters)
  File "/usr/local/lib/python3.6/dist-packages/dolfin/parameter/__init__.py", line 38, in update
    self[key].update(params[key])
  File "/usr/local/lib/python3.6/dist-packages/dolfin/parameter/__init__.py", line 40, in update
    self[key] = params[key]
TypeError: __setitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: dolfin.cpp.parameter.Parameters, arg0: str, arg1: none) -> None
    2. (self: dolfin.cpp.parameter.Parameters, arg0: str, arg1: bool) -> None
    3. (self: dolfin.cpp.parameter.Parameters, arg0: str, arg1: str) -> None
    4. (self: dolfin.cpp.parameter.Parameters, arg0: str, arg1: int) -> None
    5. (self: dolfin.cpp.parameter.Parameters, arg0: str, arg1: float) -> None
    6. (self: dolfin.cpp.parameter.Parameters, arg0: str, arg1: dolfin.cpp.parameter.Parameters) -> None

Invoked with: <dolfin.cpp.parameter.Parameters object at 0x7f1ab69a0c00>, 'absolute_tolerance', <dolfin.cpp.parameter.Parameter object at 0x7f1aba2335a8>
```

**Comment by jorgensd** [comment]
Solved in https://bitbucket.org/dolfin-adjoint/pyadjoint/pull-requests/85/support-of-more-solver-types
