### ISSUE TITLE
Subfunctions does not work with FunctionAssigner

### ISSUE THREAD

**Issue by finsberg** [dolfin-adjoint/pyadjoint#39]
I have the following example which does work in pure dolfin, but which does not work with dolfin_adjoint
```python
# subfunction_assign.py
import dolfin

# from dolfin import Function, FunctionAssigner, UnitSquareMesh
from dolfin_adjoint import Function, FunctionAssigner, UnitSquareMesh

mesh = UnitSquareMesh(3, 3)
V = dolfin.VectorFunctionSpace(mesh, "R", 0, dim=2)
v = Function(V)

W = V.sub(0).collapse()
w = Function(W)
fa = FunctionAssigner(W, V.sub(0))
print("v: ", hasattr(v, "_ad_will_add_as_dependency"))
print("v.sub(0): ", hasattr(v.sub(0), "_ad_will_add_as_dependency"))
fa.assign(w, v.sub(0))
```

The output from this is 
```
$ python subfunction_assign.py
v:  True
v.sub(0):  False
Traceback (most recent call last):
  File "subfunction_assign.py", line 15, in <module>
    fa.assign(w, v.sub(0))
  File "/Users/henriknf/miniconda3/envs/pyadjoint/lib/python3.7/site-packages/fenics_adjoint/types/function_assigner.py", line 34, in assign
    block = FunctionAssignerBlock(self, inputs)
  File "/Users/henriknf/miniconda3/envs/pyadjoint/lib/python3.7/site-packages/fenics_adjoint/blocks/function_assigner.py", line 13, in __init__
    self.add_dependency(i)
  File "/Users/henriknf/miniconda3/envs/pyadjoint/lib/python3.7/site-packages/pyadjoint/block.py", line 52, in add_dependency
    dep._ad_will_add_as_dependency()
AttributeError: 'Function' object has no attribute '_ad_will_add_as_dependency'
```
Is this a bug, or should I do this differently?

**Comment by sebastkm** [comment]
It's a missing feature that has an easy workaround.
Basically, we support `split`, but lack support for `sub`. But you can just do the following:

```
v_sub = v.split()
fa.assign(w, v_sub[0])
```
