### ISSUE TITLE
Taylor remainder convergence test demo on the website did not work

### ISSUE THREAD

**Issue by meiyue1989** [dolfin-adjoint/pyadjoint#65]
Dear all,

I am trying to run the Taylor remainder convergence test shown in the dolfin-adjoint website (http://www.dolfin-adjoint.org/en/latest/documentation/verification.html). The program is named “tutorial4.py“. The error message is shown below:

Traceback (most recent call last):

File "/home/meiyue/research-bk/Fenics_project/optimization/tutorial4.py", line 31, in <module>
    dJdnu = compute_gradient(J, nu)

File "/opt/software/anaconda3/envs/fenicsproject/lib/python3.9/site-packages/dolfin_adjoint-2019.1.1-py3.9.egg/pyadjoint/drivers.py", line 31, in compute_gradient
    grads = [i.get_derivative(options=options) for i in m]

File "/opt/software/anaconda3/envs/fenicsproject/lib/python3.9/site-packages/dolfin_adjoint-2019.1.1-py3.9.egg/pyadjoint/drivers.py", line 31, in <listcomp>
    grads = [i.get_derivative(options=options) for i in m]

File "/opt/software/anaconda3/envs/fenicsproject/lib/python3.9/site-packages/dolfin_adjoint-2019.1.1-py3.9.egg/fenics_adjoint/types/constant.py", line 42, in get_derivative
    return self._ad_convert_type(self.adj_value, options=options)

AttributeError: 'Constant' object has no attribute 'adj_value'

Thus, I changed this line “dJdnu = compute_gradient(J, nu)” by ”dJdnu = compute_gradient(J, Constant(nu))”. However, even I did this and ran the code for more than 10 mins, I found the code keep running the Newton’s iteration without showing the convengence information. I would like to known how to get it fixed.

‌

All the best,

Yue Mei

**Comment by jorgensd** [comment]
Please add a minimal code example that reproduces the error message or the "stuck" behavior.

**Comment by jorgensd** [comment]
The code snippet I posted above run using the docker image: 
`quay.io/dolfinadjoint/pyadjoint:latest`
giving the results
```bash
Computed residuals: [8.789639391915973e-07, 2.2008124739463018e-07, 5.506293102116482e-08, 1.3771065246897553e-08]
Computed convergence rates: [1.9977677560482001, 1.9988829095093468, 1.9994412451809673]
```

You need to provide a minimal code example reproducing the behavior you  describe for us to be able to help you.

**Comment by meiyue1989** [comment]
Sorry. I directly downloaded the code without modifying anything from the website, thus I only provided the name of the program in my previous comment. 

Yes. This is the code I tried to run. It did not work for me. The error message has been shown in my privious comments. I did not run that code in the docker container. I installed the fenics on the anaconda and then installed the adjoint_dolfin.  I can run optimization  problems successfully, but for this simple tutorial program, it did not work. 

Based on the tuorial documentation, "  dJdnu = compute_gradient(J, nu)" should be "dJdnu = compute_gradient(J, Control(nu))"? Is it correct?

**Comment by sebastkm** [comment]
Yes, you are correct. It should be `dJdnu = compute_gradient(J, Control(nu))`

How did you install dolfin-adjoint? Using pip? Or conda install?

**Comment by meiyue1989** [comment]
I installed via "pip install git+https://github.com/dolfin-adjoint/pyadjoint.git@2019.1.0".  
Even if I corrected  "dJdnu = compute_gradient(J, Control(nu))" and run the code, it keeps doing the Newton's iteration. I cannot see the following information:

Computed residuals: [8.789639391915973e-07, 2.2008124739463018e-07, 5.506293102116482e-08, 1.3771065246897553e-08]
Computed convergence rates: [1.9977677560482001, 1.9988829095093468, 1.9994412451809673]
