### ISSUE TITLE
TSFC-Interface Bug? IndexError: tuple index out of range

### ISSUE THREAD

**Issue by medinaeder** [dolfin-adjoint/pyadjoint#67]
I am running into the following issue
```
Traceback (most recent call last):
  File "/home/e/Desktop/arclength/ac-second.py", line 169, in <module>
    dj = Jhat.derivative()
  File "/home/e/Software/firedrake/firedrake/src/pyadjoint/pyadjoint/reduced_functional.py", line 61, in derivative
    derivatives = compute_gradient(self.functional,
  File "/home/e/Software/firedrake/firedrake/src/pyadjoint/pyadjoint/drivers.py", line 29, in compute_gradient
    tape.evaluate_adj(markings=True)
  File "/home/e/Software/firedrake/firedrake/src/pyadjoint/pyadjoint/tape.py", line 140, in evaluate_adj
    self._blocks[i].evaluate_adj(markings=markings)
  File "/home/e/Software/firedrake/firedrake/src/pyadjoint/pyadjoint/tape.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/home/e/Software/firedrake/firedrake/src/pyadjoint/pyadjoint/block.py", line 130, in evaluate_adj
    adj_output = self.evaluate_adj_component(inputs,
  File "/home/e/Software/firedrake/firedrake/src/pyadjoint/dolfin_adjoint_common/blocks/assembly.py", line 58, in evaluate_adj_component
    output = self.compat.assemble_adjoint_value(dform)
  File "/home/e/Software/firedrake/firedrake/src/pyadjoint/dolfin_adjoint_common/compat.py", line 123, in assemble_adjoint_value
    result = backend.assemble(*args, **kwargs)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/adjoint/assembly.py", line 18, in wrapper
    output = assemble(*args, **kwargs)
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 126, in assemble
    return assemble_form(expr, tensor, bcs, diagonal, assembly_type,
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 168, in assemble_form
    return _assemble_vector(expr, tensor, bcs, opts)
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 303, in _assemble_vector
    _assemble_expr(expr, vector, bcs, opts, _AssemblyRank.VECTOR)
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 453, in _assemble_expr
    parloops = _make_parloops(*parloop_init_args)
  File "<decorator-gen-34>", line 2, in _make_parloops
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/utils.py", line 73, in wrapper
    return f(*args, **kwargs)
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/assemble.py", line 700, in _make_parloops
    kernels = tsfc_interface.compile_form(expr, "form", parameters=form_compiler_parameters, diagonal=diagonal)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 229, in compile_form
    kinfos = TSFCKernel(f, prefix, parameters,
  File "/home/e/Software/firedrake/firedrake/src/PyOP2/pyop2/caching.py", line 178, in __new__
    key = cls._cache_key(*args, **kwargs)
  File "/home/e/Software/firedrake/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 121, in _cache_key
    + str(diagonal)).encode()).hexdigest(), form.ufl_domains()[0].comm
IndexError: tuple index out of range
```

@wence- 
I have a feeling that the bug is similar to this issue that I previously closed because I didn't encounter it any more and I couldn't find the code that caused it. 
https://github.com/firedrakeproject/tsfc/issues/236

**Comment by wence-** [comment]
What is the code you are running?

**Comment by wence-** [comment]
My crystal ball says that `form.ufl_domains()` is an empty tuple. So that we don't actually know what mesh to assemble it over. Can you check that? The question then is how that happens.

**Comment by medinaeder** [comment]
The error is popping up in the adjoint part not the forward solve part which I don't have access too. 
However, I have checked all the forms in the forward problem and everything lives in ` <Mesh #1> `.

**Comment by medinaeder** [comment]
Here is the MFE
[ac-mfe.zip](https://github.com/dolfin-adjoint/pyadjoint/files/6824246/ac-mfe.zip)

**Comment by medinaeder** [comment]
RESOLVED!!!!! I can now make the code run.
The error was that one of the domains was missing a form. Modifying firedrake to print the contents of form yielded `<empty Form> ` and this does not have a `ufl_domain` I was building a form based of a previous variable `z,lmbda = split(state)`  line 72.
In lines 131 and 132 I was assembling a functional based of these variables when I should be calling `z,lmbda = state.split()`  prior to assembly.

**This is perhaps one of the most subtle u.split() vs. split(u) I have encountered.**
